[committee]
members = [
    "celinval",
    "rahulku",
    "pnkfelix",
    "adpaco-aws",
    "feliperodri",
    "zhassan-aws",
    "remi-delmas-3000",
    "qinheping",
    "tautschnig",
    "jaisnan",
    "patricklam",
    "ranjitjhala",
    "carolynzech",
    "robdockins",
    "HuStmpHrrr",
    "Eh2406",
    "jswrenn"
]
