# This version should be updated whenever we update the version of the Rust
# standard library we currently track.

[toolchain]
channel = "nightly-2025-04-24"
components = ["llvm-tools-preview", "rustc-dev", "rust-src", "rustfmt"]
