name: Kani Metrics Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 UTC every Sunday
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update-kani-metrics:
    if: github.repository == 'model-checking/verify-rust-std'
    runs-on: ubuntu-latest
    
    steps:
    - name: Remove unnecessary software to free up disk space
      run: |
        # inspired by https://github.com/easimon/maximize-build-space/blob/master/action.yml
        df -h
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/local/.ghcup
        df -h

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    # The Kani metrics collection uses a Python script (kani_std_analysis.py), so make sure Python is installed
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Compute Kani Metrics
      run: |
        ./scripts/run-kani.sh --run metrics --with-autoharness --path ${{github.workspace}}
        rm kani-list.json

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update Kani metrics
        title: 'Update Kani Metrics'
        body: |
          This is an automated PR to update Kani metrics.
          
          The metrics have been updated by running `./scripts/run-kani.sh --run metrics`.
        branch: update-kani-metrics
        delete-branch: true
        base: main
